[auth]
site_url = "https://portal-five-jet.vercel.app"
additional_redirect_urls = ["https://portal-five-jet.vercel.app/**", "http://localhost:3000/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "60s"
otp_length = 6
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
