-- Minimal raw storage for Expandi responses
-- Run once in Supabase SQL Editor.

create table if not exists public.expandi_raw (
  id bigint generated by default as identity primary key,
  source text not null default 'expandi',
  endpoint_path text not null,
  method text not null default 'GET',
  status_code int,
  ok boolean,
  response_headers jsonb,
  response_body jsonb,
  synced_at timestamptz not null default now()
);

create index if not exists expandi_raw_synced_at_idx on public.expandi_raw (synced_at desc);
create index if not exists expandi_raw_endpoint_idx on public.expandi_raw (endpoint_path);

