create table if not exists public.linkedin_campaign_mapping (
  id bigint generated by default as identity primary key,
  raw_name text not null,
  canonical_name text not null,
  campaign_group text not null,
  phase text null,
  source text not null default 'manual',
  confidence text not null default 'exact',
  notes text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint linkedin_campaign_mapping_raw_name_key unique (raw_name)
);

create index if not exists linkedin_campaign_mapping_canonical_idx
  on public.linkedin_campaign_mapping (canonical_name);

create index if not exists linkedin_campaign_mapping_group_idx
  on public.linkedin_campaign_mapping (campaign_group);

insert into public.linkedin_campaign_mapping (
  raw_name,
  canonical_name,
  campaign_group,
  phase,
  source,
  confidence,
  notes
)
select
  c.alias as raw_name,
  c.canonical as canonical_name,
  c.canonical as campaign_group,
  null as phase,
  'campaign_name_aliases' as source,
  'exact' as confidence,
  'Seeded from existing LinkedIn alias mapping' as notes
from public.campaign_name_aliases c
where c.channel = 'linkedin'
on conflict (raw_name) do update
set
  canonical_name = excluded.canonical_name,
  campaign_group = excluded.campaign_group,
  source = excluded.source,
  confidence = excluded.confidence,
  notes = excluded.notes,
  updated_at = now();

insert into public.linkedin_campaign_mapping (
  raw_name,
  canonical_name,
  campaign_group,
  phase,
  source,
  confidence,
  notes
)
select
  c.name as raw_name,
  c.name as canonical_name,
  c.name as campaign_group,
  case
    when lower(c.name) like '%before%' then 'before'
    when lower(c.name) like '%after%' then 'after'
    else null
  end as phase,
  'expandi_campaign_catalog' as source,
  'exact' as confidence,
  'Seeded from historical campaign catalog' as notes
from public.expandi_campaign_catalog c
where c.name is not null
on conflict (raw_name) do nothing;
